# Add documentation label to any change in documentation related files
documentation:
  - any: ["docs/*", "docs/**/*", "**/README.md", "CONTRIBUTING.md"]

maintenance:
  - any:
      [
        ".vscode/*",
        ".vscode/**/*",
        ".github/*",
        ".github/**/*",
        ".reuse/*",
        "**/LICENSES/*",
        ".editorconfig",
        "**/.gitignore",
        "**/build.py",
      ]
