name: lint-project

on:
  push:
    branches-ignore: [main]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  run-component-checks:
    name: run-component-checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: run-component-checks
        uses: ./.github/actions/build-environment
        with:
          build_args: --check
  run-superlinter:
    name: run-superlinter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: lint-code-base
        uses: github/super-linter@v3
        env:
          # only validate new or edited files
          VALIDATE_ALL_CODEBASE: false
          # Disable CSS validation because we use styelint with custom packages
          VALIDATE_CSS: false
          # Disable JavaScript validation because we use eslint with custom packages
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_JSX: false
          DEFAULT_BRANCH: main
          FILTER_REGEX_EXCLUDE: (.*\.vscode/.*)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTIONS_RUNNER_DEBUG: false
          LOG_LEVEL: verbose
