name: lint-project

on:
  push:
    branches-ignore: [main]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [main]

jobs:
  build:
    name: lint-project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: lint-code-base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          FILTER_REGEX_EXCLUDE:  (.*\.vscode/.*)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: lint-python
        uses: wemake-services/wemake-python-styleguide
        with:
          path: './python-lib'