name: pr-title-linting

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, edited, synchronize]

jobs:
  pr-title-linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: pr-title-linting
        id: pr-title-linting
        uses: agenthunt/conventional-commit-checker-action@v1.0.0