name: test-action

on:
  push:
    branches-ignore: [main]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - uses: ./.github/actions/docker-test-action